<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "feedback".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $text
 * @property integer $date
 */
class Claim extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'claim';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','type','user','text'], 'required'],
            [['name','type','user','text','company'], 'string'],
            [['date','vacancy_id','user_id','resume_id'], 'integer'],
        ];
    } 

    public function beforeValidate()
    {
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function sendEmail()
    {
        $this->date = time();
        if($this->save()) {
            $text = Yii::t('app', 'New complaint received ');
            return Yii::$app->mailer->compose()
                ->setTo(Yii::$app->params['adminEmail'])
                ->setFrom(['noreplay@'.str_replace('www.','' , $_SERVER['HTTP_HOST']) => 'Noreplay'])
                ->setSubject(Yii::t('app', 'A new complaint has been received from the site ') . $_SERVER['HTTP_HOST'])
                ->setHtmlBody($text)
                ->send();
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'E-mail',
            'text' => 'Message',
            'theme' => 'Subject',
            'date' => 'Date',
        ];
    }
}
