<?php

namespace frontend\models\cabinet;

use common\models\User;
use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class PasswordInfochangeForm extends Model
{
    public $password;
    public $email;
    public $phone;
    public $passwordcheck;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['phone', 'email'], 'required'],
            [['password', 'passwordcheck'], 'required', 'when' => function ($model) {
                return $model->password != '';
            }, 'whenClient' => "function (attribute, value) {
                 return $('#passwordinfochangeform-password').val() != '';
            }"],
            [['password', 'passwordcheck'], 'string', 'min' => 6],
            ['passwordcheck', 'compare', 'compareAttribute' => 'password', 'message' => 'Пароли не совпадают'],
        ];
    }

    public function init()
    {
        $this->phone = Yii::$app->user->identity->phone;
        $this->email = Yii::$app->user->identity->email;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'phone' => 'Номер телефона',
            'email' => 'Электронная почта',
            'password' => 'Пароль',
            'passwordcheck' => 'Пароль еще раз',
        ];
    }

    public function changePasswordInfo()
    {
        Yii::$app->user->identity->setPassword($this->password);
        $userModel = User::findOne(['id' => Yii::$app->user->getId()]);

        $userModel->phone = $this->phone;
        $userModel->email = $this->email;

        if ($this->password) {
            $userModel->setPassword($this->password);
            Yii::$app->session->setFlash('success', 'Пароль изменен');
        }
        if ($userModel->save()) {
            Yii::$app->session->setFlash('success', 'Профиль обновлен');
            if ($this->password) {
                Yii::$app->session->setFlash('success', 'Профиль и пароль обновлен');
            }
        }
        return;
    }
}
